name: Build

on:
  push:
    branches:
      - 'main'
  pull_request:
  workflow_dispatch:

permissions:
  contents: write

env:
  NODE_VERSION: 18

jobs:
  build:
    name: Build
    runs-on: windows-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Deps
        run: npm install

      - name: Linting
        run: npm run lint

      #- name: Package Security Audit
      #  run: npm audit

      - name: Build Binary
        run: npm run build

      - name: Save Binary
        uses: actions/upload-artifact@v4
        with:
          name: fh5-g27-leds
          path: dist

  dependabot:
    name: Dependabot
    needs: build
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' && github.event_name == 'pull_request'}}
    steps:
      - name: Dependabot metadata
        uses: dependabot/fetch-metadata@v2.0.0
        id: metadata
        with:
          github-token: '${{ secrets.GITHUB_TOKEN }}'
      - name: Enable auto-merge for Dependabot PRs
        run: gh pr merge --auto --merge "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
